replicaCount: 1

namespace: monitoring
labels:
  app: mimir-cardicop
  env: prod
  tier: t2


image:
  repository: ghcr.io/leegin/mimir-cardicop
  tag: v0.4
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: "mimir-cardicop"
fullnameOverride: "mimir-cardicop"

serviceAccount:
  create: true
  name: "mimir-cardicop"

rbac:
  create: true

service:
  type: ClusterIP
  port: 8000

resources:
  limits:
    cpu: 300m
    memory: 500Mi
  requests:
    cpu: 200m
    memory: 250Mi

nodeSelector: {}
tolerations: []
affinity: {}

env:
  GRAFANA_URL: "http://grafana.yourdomain.com"
  GRAFANA_ADMIN_USER: "admin"
  GRAFANA_ADMIN_PASSWORD: "yourpassword"
  STORE_GATEWAY_URL: "http://mimir-store-gateway.namespace:8080"
  MIMIR_QUERY_URL: "https://grafana-mimir-query-frontend.namespace:8080"
  MIMIR_RULER_URL: "http://grafana-mimir-ruler.namespace:8080"
  MIMIR_TENANT_ID: "yourtenant"
  LOKI_QUERY_METRIC_NAME: metric:query:count15s
  LOKI_QUERY_LOOKBACK_DAYS: 7
  SERVICE_ACCOUNT_NAME: mimirtool-service-account
  EXPORTER_PORT: 8000
  EXPORT_INTERVAL_SECONDS: 86400
  TOKEN_EXPIRY_HOURS: 1
  SSL_VERIFY: "false"


